<a href="https://colab.research.google.com/github/nikhilvkth/325_Image_processing/blob/main/lossy_compression_DWT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pywt

X = np.array([[100, 50, 60, 20],
              [30,  40, 80, 70],
              [120, 110, 50, 30],
              [70,  90, 20, 40]], dtype=float)

# Let's perform row-by-row Haar transform manually first to see the intermediate steps
# Haar filter: lowpass = [1/sqrt(2), 1/sqrt(2)], highpass = [-1/sqrt(2), 1/sqrt(2)] or [1/sqrt(2), -1/sqrt(2)]
# Usually: Approx = (a+b)/sqrt(2), Detail = (a-b)/sqrt(2)

def haar_1d_step(row):
    approx = []
    detail = []
    for i in range(0, len(row), 2):
        a, b = row[i], row[i+1]
        approx.append((a + b) / np.sqrt(2))
        detail.append((a - b) / np.sqrt(2))
    return approx + detail

row_transformed = np.array([haar_1d_step(r) for r in X])
print("Row transformed (with 1/sqrt(2)):")
print(row_transformed)

# Now column transform on the row_transformed matrix
col_transformed = np.zeros_like(row_transformed)
for j in range(row_transformed.shape[1]):
    col = row_transformed[:, j]
    approx = []
    detail = []
    for i in range(0, len(col), 2):
        a, b = col[i], col[i+1]
        approx.append((a + b) / np.sqrt(2))
        detail.append((a - b) / np.sqrt(2))
    col_transformed[:, j] = approx + detail

print("\nFull 2D Haar DWT (with 1/sqrt(2)):")
print(col_transformed)

# Let's also do it without sqrt(2) scaling (i.e., using factor of 0.5 for average and difference) which is common in manual text explanations
def haar_1d_step_unscaled(row):
    approx = []
    detail = []
    for i in range(0, len(row), 2):
        a, b = row[i], row[i+1]
        approx.append((a + b) / 2)
        detail.append((a - b) / 2)
    return approx + detail

row_trans_unscaled = np.array([haar_1d_step_unscaled(r) for r in X])
print("\nRow transformed (unscaled, /2):")
print(row_trans_unscaled)

col_trans_unscaled = np.zeros_like(row_trans_unscaled)
for j in range(row_trans_unscaled.shape[1]):
    col = row_trans_unscaled[:, j]
    approx = []
    detail = []
    for i in range(0, len(col), 2):
        a, b = col[i], col[i+1]
        approx.append((a + b) / 2)
        detail.append((a - b) / 2)
    col_trans_unscaled[:, j] = approx + detail

print("\nFull 2D Haar DWT (unscaled, /2):")
print(col_trans_unscaled)

# Let's check with pywt to verify the standard implementation
coeffs = pywt.dwt2(X, 'haar')
LL, (HL, LH, HH) = coeffs
print("\nPyWavelets LL:")
print(LL)
print("PyWavelets HL:")
print(HL)
print("PyWavelets LH:")
print(LH)
print("PyWavelets HH:")
print(HH)

Row transformed (with 1/sqrt(2)):
[[106.06601718  56.56854249  35.35533906  28.28427125]
 [ 49.49747468 106.06601718  -7.07106781   7.07106781]
 [162.63455967  56.56854249   7.07106781  14.14213562]
 [113.13708499  42.42640687 -14.14213562 -14.14213562]]

Full 2D Haar DWT (with 1/sqrt(2)):
[[110. 115.  20.  25.]
 [195.  70.  -5.   0.]
 [ 40. -35.  30.  15.]
 [ 35.  10.  15.  20.]]

Row transformed (unscaled, /2):
[[ 75.  40.  25.  20.]
 [ 35.  75.  -5.   5.]
 [115.  40.   5.  10.]
 [ 80.  30. -10. -10.]]

Full 2D Haar DWT (unscaled, /2):
[[ 55.   57.5  10.   12.5]
 [ 97.5  35.   -2.5   0. ]
 [ 20.  -17.5  15.    7.5]
 [ 17.5   5.    7.5  10. ]]

PyWavelets LL:
[[110. 115.]
 [195.  70.]]
PyWavelets HL:
[[ 40. -35.]
 [ 35.  10.]]
PyWavelets LH:
[[20. 25.]
 [-5.  0.]]
PyWavelets HH:
[[30. 15.]
 [15. 20.]]
